### PR TITLE
MultiType Supports Basedir Red4Exts

### LINKED ISSUE #79: Combination Installer For CET/Redscript/Red4Ext/TweakDB/INI...
We should be able to install valid combinations of mod types. Initial version will require essentially canonical layouts, maybe we branch out later.

Examples:

- [ ] CET and Red4Ext [E-mode](https://www.nexusmods.com/cyberpunk2077/mods/3207?tab=files)
image
- [ ] All possible mod types combined in [Furigana](https://www.nexusmods.com/cyberpunk2077/mods/3775?tab=files) 
image

### PR DESCRIPTION
**Pull request by effs**
Based on #86, can merge this or both separately.

Closes #79

### CODE REVIEW

**Review by Bladehawke — COMMENTED** [review]
I'm not seeing anything that jumps out at me.  this will merge cleanly, but the stuff I added the other day (ASI) will need minor tweaks to get to build/test

**Comment by effs** [comment]
👍🏻 Gonna leave this up but will just merge it in #94, everything's merged into it..

**Comment by E1337Kat** [comment]
Should have not reverted. Hopefully when #94 is merged into here, then it can be merged again?

**Comment by E1337Kat** [comment]
all included in #98 because I got confused... So just gonna leave this closed and have the messy git history and get that in.

**Pull request merged**
